### ISSUE TITLE
Mixing case and guard raises error

### ISSUE THREAD

**Issue by mklemm2** [rasguanabana/function-pattern-matching#6]
Works:

```python
@fpm.case
@fpm.guard(msg = fpm.eq("Ping"), sender = fpm.isoftype(Actor))
def handle(self, sender, msg, payload):
	sender.tell("Pong", sender=self)
```

Doesn't work:

```python
@fpm.case(msg = "Ping")
@fpm.guard(sender = fpm.isoftype(Actor))
def handle(self, sender, msg, payload):
	sender.tell("Pong", sender=self)
```

The second case raises the following error:

```
Traceback (most recent call last):
  File "./ping_pong.py", line 14, in <module>
    class PingPong(Actor):
  File "./ping_pong.py", line 20, in PingPong
    @fpm.guard(sender = fpm.isoftype(Actor))
  File "/Users/mklemm/compile/python-arago-actors/lib/python3.7/site-packages/function_pattern_matching.py", line 551, in decorator
    decoratee._argument_guards[arg_name] = match & decoratee._argument_guards[arg_name]
  File "/Users/mklemm/compile/python-arago-actors/lib/python3.7/site-packages/function_pattern_matching.py", line 141, in checks
    raise TypeError("The right-hand operand has to be instance of GuardFunc")
TypeError: The right-hand operand has to be instance of GuardFunc
```

**Comment by mklemm2** [comment]
For my usecase, I defined myself a unified case & guard decorator:

```python
def match(**kwargs):
	guard_kwargs = {k:v for k,v in kwargs.items() if isinstance(v, fpm.GuardFunc)}
	case_kwargs = {k:v for k,v in kwargs.items() if not isinstance(v, fpm.GuardFunc)}
	if case_kwargs and guard_kwargs:
		case_kwargs = {key:fpm.eq(val) for key, val in case_kwargs.items()}
		guard_kwargs.update(case_kwargs)
		case_kwargs = {}
	def decorator(decoratee):
		return (
			fpm.case(**case_kwargs)(fpm.guard(**guard_kwargs)(decoratee))
			if guard_kwargs
			else fpm.case(**case_kwargs)(decoratee)
		)
	return decorator
```

In case there are  guard functions and exact values in the arguments, I simply turn the latter into fpm.eq() instances.

Works for me.
